# Generated by Django 5.2.12 on 2026-03-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='দানের শিরোনাম')),
                ('description', models.TextField(verbose_name='বর্ণনা')),
                ('photo', models.ImageField(upload_to='donations/', verbose_name='ছবি')),
                ('donation_date', models.DateField(blank=True, null=True, verbose_name='দানের তারিখ')),
                ('amount', models.CharField(blank=True, max_length=100, verbose_name='পরিমাণ')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='সাজানোর ক্রম')),
            ],
            options={
                'ordering': ['ordering', '-donation_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='নাম')),
                ('designation', models.CharField(max_length=150, verbose_name='পদবি')),
                ('photo', models.ImageField(upload_to='members/', verbose_name='ছবি')),
                ('bio', models.TextField(blank=True, verbose_name='সংক্ষিপ্ত পরিচিতি')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='সাজানোর ক্রম')),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PresidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='নাম')),
                ('designation', models.CharField(default='সভাপতি', max_length=150, verbose_name='পদবি')),
                ('photo', models.ImageField(upload_to='president/', verbose_name='ছবি')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'President',
                'verbose_name_plural': 'President',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='প্রজেক্টের নাম')),
                ('description', models.TextField(verbose_name='বর্ণনা')),
                ('screenshot', models.ImageField(upload_to='projects/', verbose_name='স্ক্রিনশট')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='তারিখ')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='সাজানোর ক্রম')),
            ],
            options={
                'ordering': ['ordering', '-project_date', 'title'],
            },
        ),
    ]
