# Generated by Django 5.2.12 on 2026-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook link'),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn link'),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='WhatsApp number'),
        ),
    ]
