# Generated by Django 5.2.12 on 2026-03-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_facebook_url_member_linkedin_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VicePresidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='নাম')),
                ('designation', models.CharField(default='সহ-সভাপতি', max_length=150, verbose_name='পদবি')),
                ('photo', models.ImageField(upload_to='vice-president/', verbose_name='ছবি')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vice President',
                'verbose_name_plural': 'Vice President',
                'ordering': ['-created_at'],
            },
        ),
    ]
