# Generated by Django 5.2.12 on 2026-03-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vicepresidentmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='নাম')),
                ('designation', models.CharField(default='উপদেষ্টা', max_length=150, verbose_name='পদবি')),
                ('photo', models.ImageField(upload_to='advisors/', verbose_name='ছবি')),
                ('message', models.TextField(blank=True, verbose_name='বার্তা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='সাজানোর ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advisor',
                'verbose_name_plural': 'Advisors',
                'ordering': ['ordering', '-created_at', 'name'],
            },
        ),
    ]
